# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(verbose_name='Date Of Birth')),
                ('semester', models.IntegerField()),
                ('interests', models.CharField(max_length=300)),
                ('description', models.TextField(help_text='A brief bio of the student')),
                ('picture', models.FileField(upload_to=b'')),
                ('house', models.CharField(max_length=100)),
            ],
        ),
    ]
