# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20170710_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notable_alumini', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('photo', models.FileField(blank=True, null=True, upload_to=b'')),
                ('colors', models.CharField(max_length=200)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Faculty')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.House'),
        ),
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
