# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_acheivement_alumini_infrastructure_news_photo_result_rule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acheivement',
            old_name='stu_name',
            new_name='student_name',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='stu_name',
            new_name='student_name',
        ),
    ]
