# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20170710_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='sub_name',
            new_name='subject_name',
        ),
    ]
