# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20170710_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='qualification',
            field=models.CharField(choices=[('O.W.L', 'Owl'), ('N.E.W.T', 'Newt'), ('Above N.E.W.T', 'Above Newt')], max_length=30),
        ),
    ]
