# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20170711_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='colors',
        ),
        migrations.AddField(
            model_name='house',
            name='color1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='House Color 1'),
        ),
        migrations.AddField(
            model_name='house',
            name='color2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='House Color 2'),
        ),
        migrations.AddField(
            model_name='house',
            name='color3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Text Color'),
        ),
    ]
