# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20170711_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumini',
            name='joining_date',
            field=models.DateField(help_text='Date of joining this position (in yyyy-mm-dd format)'),
        ),
    ]
